version: '2'
services:
    onlinescheduler-app:
        image: onlinescheduler
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://onlinescheduler-mariadb:3306/onlinescheduler
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    onlinescheduler-mariadb:
        extends:
            file: mariadb.yml
            service: onlinescheduler-mariadb
